---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-server
  name: config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: NodePort
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: shreya7123/bookmyslot:book-slot_config-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
        - name: servername_eureka
          value: "eureka-server"
...
