---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server
  type: NodePort
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: shreya7123/bookmyslot:book-slot_eureka-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
...
